const list = [
  {
    id: 0,
    img: "picture/p_disneyplus_dashingthroughthesnow_v2_2580_ba0fc221.jpg",
    title: "Dashing Through the Snow",
    poster:
      "picture/pp_disneyplus_dashingthroughthesnow_herobanner_2580_4128717c.jpg",
    logo: "picture/itme.png",
  },
  {
    id: 1,
    img: "picture/p_disneyplusoriginals_ahsoka_midseason_1784_v1_935ef8b2.jpg",
    title: "Ahsoka",
    poster: "picture/hihi.jpg",
    logo: "picture/as.png",
  },
  {
    id: 2,
    img: "picture/p_disneyplusoriginals_goosebumps_v2_2214_1_197bcd1a.jpg",
    title: "Goosebumps",
    poster: "picture/dhdf.jpg",
    logo: "picture/6ergfe.png",
  },
  {
    id: 3,
    img: "picture/p_disneyplusoriginals_hsmtmts_s4_2150_v2_1cddd0b6.jpg",
    title: "High School Musical: The Musical: The Series Season 4",
    poster: "picture/dsd.jpg",
    logo: "picture/sds.png",
  },
  {
    id: 4,
    img: "picture/p_disneyplusoriginals_launchpad_s2_2515_v1_bd13b664.jpg",
    title: "Launchpad Season 2",
    poster: "picture/fsdf.jpg",
    logo: "picture/gf.png",
  },
  {
    id: 5,
    img: "picture/p_disneyplusoriginals_loki_s2_finale_poster_v1_613_36711b22.jpg",
    title: "Loki Season 2",
    poster: "picture/sc.jpg",
    logo: "picture/vdsssss.png",
  },
  {
    id: 6,
    img: "picture/p_iamgroot_s02_v3_2318_428799e4.jpg",
    title: "I Am Groot Season 2",
    poster: "picture/dssdcc.jpg",
    logo: "picture/sdasd.png",
  },
  {
    id: 7,
    img: "picture/p_marvelstudiosassembled_22304_435cd969.jpg",
    title: "Marvel Studios’ Assembled",
    poster: "picture/đsdsd.jpg",
    logo: "picture/dfddđ.png",
  },
  {
    id: 8,
    img: "picture/p_ondisney_legodisneyprincessthecastlequest_v3_2293_d80063ae.jpg",
    title: "LEGO® Disney Princess: The Castle Quest",
    poster: "picture/ddjkđcccxz.jpg",
    logo: "picture/gdsfgzsdfsdgdf.png",
  },
  {
    id: 9,
    img: "picture/p_ondisneyplus_behindtheattraction_s02_v2_2581_ec1c40fb.jpg",
    title: "Behind the Attraction Season 2",
    poster: "picture/6ggg.jpg",
    logo: "picture/csdsds7.png",
  },
  {
    id: 10,
    img: "picture/p_ondisneyplus_langlangplaysdisney_poster_v2_2182_9054755d.jpg",
    title: "Lang Lang Plays Disney",
    poster: "picture/sdfgsd.jpg",
    logo: "picture/rgerg.png",
  },
  {
    id: 11,
    img: "picture/p_ondisneyplus_thesantaclauses_s02_v4_2506_82de499d.jpg",
    title: "The Santa Clauses Season 2",
    poster: "picture/dfsafse.jpg",
    logo: "picture/ewrtwe.png",
  },
  {
    id: 12,
    img: "picture/pp_disneyplus_legomarvelavengerscodered_poster_v1_2533_066fe74d.jpg",
    title: "LEGO® Marvel Avengers: Code Red",
    poster: "picture/dfsdsff.jpg",
    logo: "picture/sdadfsh.png",
  },
  {
    id: 13,
    img: "picture/pp_disneyplusoriginals_animalsupclose_poster_v2_2295_ffdbe6b0.jpg",
    title: "Animals Up Close with Bertie Gregory",
    poster: "picture/vgadfasdfg.jpg",
    logo: "picture/fdfd.png",
  },
  {
    id: 14,
    img: "picture/pp_ondisneyplus_goodchemistrythestoryofelemental_poster_a3b2cfcd.jpg",
    title: "Good Chemistry: The Story of Elemental",
    poster: "picture/èwefw.jpg",
    logo: "picture/efwefwe.png",
  },
  {
    id: 15,
    img: "picture/p_disneyplusoriginals_saturdays_v2_1488_955eb3f3.jpg",
    title: "Saturdays",
    poster: "picture/fdfsdsd.jpg",
    logo: "picture/tewfdsd.png",
  },
  {
    id: 16,
    img: "picture/p_ondisneyplus_diaryofawimpykidchristmascabinfever_v4_2_b2fd113e.jpg",
    title: "Diary of a Wimpy Kid Christmas: Cabin Fever",
    poster: "picture/fsdfasdf.jpg",
    logo: "picture/dsasdas.png",
  },
  {
    id: 17,
    img: "picture/p_ondisneyplus_dr_2645317a.jpg",
    title: "Doctor Who",
    poster: "picture/dsdgg.jpg",
    logo: "picture/rewegfsdddddđa.png",
  },
  {
    id: 18,
    img: "picture/p_disneyplusoriginals_secretsofsulphursprings_s03_1491_7e41fa31.jpg",
    title: "Secrets of Sulphur Springs Season 3",
    poster: "picture/fasfdasdf.jpg",
    logo: "picture/dfdsfgg.png",
  },
  {
    id: 19,
    img: "picture/p_disneyplusoriginals_prompact_v3_846_670a58bc.jpg",
    title: "Prom Pact",
    poster: "picture/sdfsdfsg.jpg",
    logo: "picture/sadfasdf.png",
  },
];
const list2 = [
  {
    id: 1,
    img: "picture/p_disneyplusoriginals_winorlose_poster_800_v2_c40df05c.jpg",
    title: "Win or Lose",
  },
  {
    id: 2,
    img: "picture/p_disneyplusoriginals_iwaju_poster_801_v2_ac46b9b0.jpg",
    title: "Iwájú",
  },
  {
    id: 3,
    img: "picture/p_disneyplusoriginals_x-men97_ticketnumber_v2_610_b5ba7816.jpg",
    title: "X-Men ’97",
  },
  {
    id: 4,
    img: "picture/p_agathacovenofchaos_609_23888398.jpg",
    title: "Agatha: Coven of Chaos",
  },
  {
    id: 5,
    img: "picture/p_disneyplusoriginals_ironheart_20658_1_ab6e2070.jpg",
    title: "Ironheart",
  },
  {
    id: 6,
    img: "picture/p_daredevilbornagain_614_404a05e5.jpg",
    title: "Daredevil: Born Again",
  },
  {
    id: 7,
    img: "picture/p_disneyplusoriginals_spidermanfreshmanyear_22213_1ab35999.jpg",
    title: "Spider-Man: Freshman Year",
  },
];

export { list, list2 };
